// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheInteract_MapInsert_FullMethodName = "/CacheInteract/MapInsert"
	CacheInteract_MapFetch_FullMethodName  = "/CacheInteract/MapFetch"
)

// CacheInteractClient is the client API for CacheInteract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheInteractClient interface {
	MapInsert(ctx context.Context, in *MapInsertInput, opts ...grpc.CallOption) (*MapInsertResult, error)
	MapFetch(ctx context.Context, in *MapFetchInput, opts ...grpc.CallOption) (*MapFetchResult, error)
}

type cacheInteractClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheInteractClient(cc grpc.ClientConnInterface) CacheInteractClient {
	return &cacheInteractClient{cc}
}

func (c *cacheInteractClient) MapInsert(ctx context.Context, in *MapInsertInput, opts ...grpc.CallOption) (*MapInsertResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapInsertResult)
	err := c.cc.Invoke(ctx, CacheInteract_MapInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheInteractClient) MapFetch(ctx context.Context, in *MapFetchInput, opts ...grpc.CallOption) (*MapFetchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapFetchResult)
	err := c.cc.Invoke(ctx, CacheInteract_MapFetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheInteractServer is the server API for CacheInteract service.
// All implementations must embed UnimplementedCacheInteractServer
// for forward compatibility.
type CacheInteractServer interface {
	MapInsert(context.Context, *MapInsertInput) (*MapInsertResult, error)
	MapFetch(context.Context, *MapFetchInput) (*MapFetchResult, error)
	mustEmbedUnimplementedCacheInteractServer()
}

// UnimplementedCacheInteractServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheInteractServer struct{}

func (UnimplementedCacheInteractServer) MapInsert(context.Context, *MapInsertInput) (*MapInsertResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapInsert not implemented")
}
func (UnimplementedCacheInteractServer) MapFetch(context.Context, *MapFetchInput) (*MapFetchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapFetch not implemented")
}
func (UnimplementedCacheInteractServer) mustEmbedUnimplementedCacheInteractServer() {}
func (UnimplementedCacheInteractServer) testEmbeddedByValue()                       {}

// UnsafeCacheInteractServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheInteractServer will
// result in compilation errors.
type UnsafeCacheInteractServer interface {
	mustEmbedUnimplementedCacheInteractServer()
}

func RegisterCacheInteractServer(s grpc.ServiceRegistrar, srv CacheInteractServer) {
	// If the following call pancis, it indicates UnimplementedCacheInteractServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheInteract_ServiceDesc, srv)
}

func _CacheInteract_MapInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapInsertInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheInteractServer).MapInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheInteract_MapInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheInteractServer).MapInsert(ctx, req.(*MapInsertInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheInteract_MapFetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapFetchInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheInteractServer).MapFetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheInteract_MapFetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheInteractServer).MapFetch(ctx, req.(*MapFetchInput))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheInteract_ServiceDesc is the grpc.ServiceDesc for CacheInteract service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheInteract_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CacheInteract",
	HandlerType: (*CacheInteractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MapInsert",
			Handler:    _CacheInteract_MapInsert_Handler,
		},
		{
			MethodName: "MapFetch",
			Handler:    _CacheInteract_MapFetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
