// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapInsertInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertInput) Reset() {
	*x = MapInsertInput{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertInput) ProtoMessage() {}

func (x *MapInsertInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertInput.ProtoReflect.Descriptor instead.
func (*MapInsertInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *MapInsertInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapInsertInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapFetchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchInput) Reset() {
	*x = MapFetchInput{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchInput) ProtoMessage() {}

func (x *MapFetchInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchInput.ProtoReflect.Descriptor instead.
func (*MapFetchInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *MapFetchInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapDeleteInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteInput) Reset() {
	*x = MapDeleteInput{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteInput) ProtoMessage() {}

func (x *MapDeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteInput.ProtoReflect.Descriptor instead.
func (*MapDeleteInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *MapDeleteInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapInsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertResult) Reset() {
	*x = MapInsertResult{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertResult) ProtoMessage() {}

func (x *MapInsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertResult.ProtoReflect.Descriptor instead.
func (*MapInsertResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *MapInsertResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MapFetchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchResult) Reset() {
	*x = MapFetchResult{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchResult) ProtoMessage() {}

func (x *MapFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchResult.ProtoReflect.Descriptor instead.
func (*MapFetchResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *MapFetchResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapDeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteResult) Reset() {
	*x = MapDeleteResult{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteResult) ProtoMessage() {}

func (x *MapDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteResult.ProtoReflect.Descriptor instead.
func (*MapDeleteResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *MapDeleteResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\"8\n" +
	"\x0eMapInsertInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"!\n" +
	"\rMapFetchInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\"\n" +
	"\x0eMapDeleteInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x0fMapInsertResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"&\n" +
	"\x0eMapFetchResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\")\n" +
	"\x0fMapDeleteResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\x9c\x01\n" +
	"\rCacheInteract\x12.\n" +
	"\tMapInsert\x12\x0f.MapInsertInput\x1a\x10.MapInsertResult\x12+\n" +
	"\bMapFetch\x12\x0e.MapFetchInput\x1a\x0f.MapFetchResult\x12.\n" +
	"\tMapDelete\x12\x0f.MapDeleteInput\x1a\x10.MapDeleteResultB\bZ\x06proto/b\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_data_proto_goTypes = []any{
	(*MapInsertInput)(nil),  // 0: MapInsertInput
	(*MapFetchInput)(nil),   // 1: MapFetchInput
	(*MapDeleteInput)(nil),  // 2: MapDeleteInput
	(*MapInsertResult)(nil), // 3: MapInsertResult
	(*MapFetchResult)(nil),  // 4: MapFetchResult
	(*MapDeleteResult)(nil), // 5: MapDeleteResult
}
var file_data_proto_depIdxs = []int32{
	0, // 0: CacheInteract.MapInsert:input_type -> MapInsertInput
	1, // 1: CacheInteract.MapFetch:input_type -> MapFetchInput
	2, // 2: CacheInteract.MapDelete:input_type -> MapDeleteInput
	3, // 3: CacheInteract.MapInsert:output_type -> MapInsertResult
	4, // 4: CacheInteract.MapFetch:output_type -> MapFetchResult
	5, // 5: CacheInteract.MapDelete:output_type -> MapDeleteResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
