// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapInsertInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertInput) Reset() {
	*x = MapInsertInput{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertInput) ProtoMessage() {}

func (x *MapInsertInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertInput.ProtoReflect.Descriptor instead.
func (*MapInsertInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *MapInsertInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapInsertInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapFetchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchInput) Reset() {
	*x = MapFetchInput{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchInput) ProtoMessage() {}

func (x *MapFetchInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchInput.ProtoReflect.Descriptor instead.
func (*MapFetchInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *MapFetchInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapDeleteInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteInput) Reset() {
	*x = MapDeleteInput{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteInput) ProtoMessage() {}

func (x *MapDeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteInput.ProtoReflect.Descriptor instead.
func (*MapDeleteInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *MapDeleteInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapInsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertResult) Reset() {
	*x = MapInsertResult{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertResult) ProtoMessage() {}

func (x *MapInsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertResult.ProtoReflect.Descriptor instead.
func (*MapInsertResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *MapInsertResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MapFetchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchResult) Reset() {
	*x = MapFetchResult{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchResult) ProtoMessage() {}

func (x *MapFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchResult.ProtoReflect.Descriptor instead.
func (*MapFetchResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *MapFetchResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapDeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteResult) Reset() {
	*x = MapDeleteResult{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteResult) ProtoMessage() {}

func (x *MapDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteResult.ProtoReflect.Descriptor instead.
func (*MapDeleteResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *MapDeleteResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type QueueInsertInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInsertInput) Reset() {
	*x = QueueInsertInput{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInsertInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInsertInput) ProtoMessage() {}

func (x *QueueInsertInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInsertInput.ProtoReflect.Descriptor instead.
func (*QueueInsertInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *QueueInsertInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueueInsertInput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueueInsertOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInsertOutput) Reset() {
	*x = QueueInsertOutput{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInsertOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInsertOutput) ProtoMessage() {}

func (x *QueueInsertOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInsertOutput.ProtoReflect.Descriptor instead.
func (*QueueInsertOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *QueueInsertOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type QueueRemoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemoveInput) Reset() {
	*x = QueueRemoveInput{}
	mi := &file_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveInput) ProtoMessage() {}

func (x *QueueRemoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveInput.ProtoReflect.Descriptor instead.
func (*QueueRemoveInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{8}
}

func (x *QueueRemoveInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type QueueRemoveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemoveOutput) Reset() {
	*x = QueueRemoveOutput{}
	mi := &file_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemoveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveOutput) ProtoMessage() {}

func (x *QueueRemoveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveOutput.ProtoReflect.Descriptor instead.
func (*QueueRemoveOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{9}
}

func (x *QueueRemoveOutput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertToSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSetInput) Reset() {
	*x = InsertToSetInput{}
	mi := &file_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSetInput) ProtoMessage() {}

func (x *InsertToSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSetInput.ProtoReflect.Descriptor instead.
func (*InsertToSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{10}
}

func (x *InsertToSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InsertToSetInput) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertToSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSetOutput) Reset() {
	*x = InsertToSetOutput{}
	mi := &file_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSetOutput) ProtoMessage() {}

func (x *InsertToSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSetOutput.ProtoReflect.Descriptor instead.
func (*InsertToSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{11}
}

func (x *InsertToSetOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetSetValuesInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetValuesInput) Reset() {
	*x = GetSetValuesInput{}
	mi := &file_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetValuesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetValuesInput) ProtoMessage() {}

func (x *GetSetValuesInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetValuesInput.ProtoReflect.Descriptor instead.
func (*GetSetValuesInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{12}
}

func (x *GetSetValuesInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSetValuesOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetValuesOutput) Reset() {
	*x = GetSetValuesOutput{}
	mi := &file_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetValuesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetValuesOutput) ProtoMessage() {}

func (x *GetSetValuesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetValuesOutput.ProtoReflect.Descriptor instead.
func (*GetSetValuesOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{13}
}

func (x *GetSetValuesOutput) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetHasMemberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHasMemberInput) Reset() {
	*x = SetHasMemberInput{}
	mi := &file_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHasMemberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHasMemberInput) ProtoMessage() {}

func (x *SetHasMemberInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHasMemberInput.ProtoReflect.Descriptor instead.
func (*SetHasMemberInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{14}
}

func (x *SetHasMemberInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetHasMemberInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetHasMemberOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasValue      bool                   `protobuf:"varint,1,opt,name=hasValue,proto3" json:"hasValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHasMemberOutput) Reset() {
	*x = SetHasMemberOutput{}
	mi := &file_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHasMemberOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHasMemberOutput) ProtoMessage() {}

func (x *SetHasMemberOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHasMemberOutput.ProtoReflect.Descriptor instead.
func (*SetHasMemberOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{15}
}

func (x *SetHasMemberOutput) GetHasValue() bool {
	if x != nil {
		return x.HasValue
	}
	return false
}

type SetRemoveMemberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoveMemberInput) Reset() {
	*x = SetRemoveMemberInput{}
	mi := &file_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveMemberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveMemberInput) ProtoMessage() {}

func (x *SetRemoveMemberInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveMemberInput.ProtoReflect.Descriptor instead.
func (*SetRemoveMemberInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{16}
}

func (x *SetRemoveMemberInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRemoveMemberInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRemoveMemberOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoveMemberOutput) Reset() {
	*x = SetRemoveMemberOutput{}
	mi := &file_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveMemberOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveMemberOutput) ProtoMessage() {}

func (x *SetRemoveMemberOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveMemberOutput.ProtoReflect.Descriptor instead.
func (*SetRemoveMemberOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{17}
}

func (x *SetRemoveMemberOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type InsertToSortedSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	MainKey       string                 `protobuf:"bytes,3,opt,name=mainKey,proto3" json:"mainKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSortedSetInput) Reset() {
	*x = InsertToSortedSetInput{}
	mi := &file_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSortedSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSortedSetInput) ProtoMessage() {}

func (x *InsertToSortedSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSortedSetInput.ProtoReflect.Descriptor instead.
func (*InsertToSortedSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{18}
}

func (x *InsertToSortedSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InsertToSortedSetInput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *InsertToSortedSetInput) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

type InsertToSortedSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSortedSetOutput) Reset() {
	*x = InsertToSortedSetOutput{}
	mi := &file_data_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSortedSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSortedSetOutput) ProtoMessage() {}

func (x *InsertToSortedSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSortedSetOutput.ProtoReflect.Descriptor instead.
func (*InsertToSortedSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{19}
}

func (x *InsertToSortedSetOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type RemoveFromSortedSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MainKey       string                 `protobuf:"bytes,2,opt,name=mainKey,proto3" json:"mainKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromSortedSetInput) Reset() {
	*x = RemoveFromSortedSetInput{}
	mi := &file_data_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromSortedSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSortedSetInput) ProtoMessage() {}

func (x *RemoveFromSortedSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSortedSetInput.ProtoReflect.Descriptor instead.
func (*RemoveFromSortedSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveFromSortedSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RemoveFromSortedSetInput) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

type RemoveFromSortedSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromSortedSetOutput) Reset() {
	*x = RemoveFromSortedSetOutput{}
	mi := &file_data_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromSortedSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromSortedSetOutput) ProtoMessage() {}

func (x *RemoveFromSortedSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromSortedSetOutput.ProtoReflect.Descriptor instead.
func (*RemoveFromSortedSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveFromSortedSetOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetScoreSortedSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MainKey       string                 `protobuf:"bytes,2,opt,name=mainKey,proto3" json:"mainKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSortedSetInput) Reset() {
	*x = GetScoreSortedSetInput{}
	mi := &file_data_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSortedSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSortedSetInput) ProtoMessage() {}

func (x *GetScoreSortedSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSortedSetInput.ProtoReflect.Descriptor instead.
func (*GetScoreSortedSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{22}
}

func (x *GetScoreSortedSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetScoreSortedSetInput) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

type GetScoreSortedSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreSortedSetOutput) Reset() {
	*x = GetScoreSortedSetOutput{}
	mi := &file_data_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreSortedSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreSortedSetOutput) ProtoMessage() {}

func (x *GetScoreSortedSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreSortedSetOutput.ProtoReflect.Descriptor instead.
func (*GetScoreSortedSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{23}
}

func (x *GetScoreSortedSetOutput) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetRankSortedSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MainKey       string                 `protobuf:"bytes,2,opt,name=mainKey,proto3" json:"mainKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankSortedSetInput) Reset() {
	*x = GetRankSortedSetInput{}
	mi := &file_data_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankSortedSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankSortedSetInput) ProtoMessage() {}

func (x *GetRankSortedSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankSortedSetInput.ProtoReflect.Descriptor instead.
func (*GetRankSortedSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{24}
}

func (x *GetRankSortedSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRankSortedSetInput) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

type GetRankSortedSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankSortedSetOutput) Reset() {
	*x = GetRankSortedSetOutput{}
	mi := &file_data_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankSortedSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankSortedSetOutput) ProtoMessage() {}

func (x *GetRankSortedSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankSortedSetOutput.ProtoReflect.Descriptor instead.
func (*GetRankSortedSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{25}
}

func (x *GetRankSortedSetOutput) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetRankMembersInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainKey       string                 `protobuf:"bytes,1,opt,name=mainKey,proto3" json:"mainKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankMembersInput) Reset() {
	*x = GetRankMembersInput{}
	mi := &file_data_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankMembersInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankMembersInput) ProtoMessage() {}

func (x *GetRankMembersInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankMembersInput.ProtoReflect.Descriptor instead.
func (*GetRankMembersInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{26}
}

func (x *GetRankMembersInput) GetMainKey() string {
	if x != nil {
		return x.MainKey
	}
	return ""
}

type GetRankMembersOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MembersAndScore []*ScoreAndName        `protobuf:"bytes,1,rep,name=membersAndScore,proto3" json:"membersAndScore,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRankMembersOutput) Reset() {
	*x = GetRankMembersOutput{}
	mi := &file_data_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankMembersOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankMembersOutput) ProtoMessage() {}

func (x *GetRankMembersOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankMembersOutput.ProtoReflect.Descriptor instead.
func (*GetRankMembersOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{27}
}

func (x *GetRankMembersOutput) GetMembersAndScore() []*ScoreAndName {
	if x != nil {
		return x.MembersAndScore
	}
	return nil
}

type ScoreAndName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreAndName) Reset() {
	*x = ScoreAndName{}
	mi := &file_data_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreAndName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreAndName) ProtoMessage() {}

func (x *ScoreAndName) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreAndName.ProtoReflect.Descriptor instead.
func (*ScoreAndName) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{28}
}

func (x *ScoreAndName) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreAndName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\"8\n" +
	"\x0eMapInsertInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"!\n" +
	"\rMapFetchInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\"\n" +
	"\x0eMapDeleteInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x0fMapInsertResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"&\n" +
	"\x0eMapFetchResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\")\n" +
	"\x0fMapDeleteResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\":\n" +
	"\x10QueueInsertInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"+\n" +
	"\x11QueueInsertOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"$\n" +
	"\x10QueueRemoveInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11QueueRemoveOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\":\n" +
	"\x10InsertToSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"+\n" +
	"\x11InsertToSetOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"%\n" +
	"\x11GetSetValuesInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\",\n" +
	"\x12GetSetValuesOutput\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\";\n" +
	"\x11SetHasMemberInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"0\n" +
	"\x12SetHasMemberOutput\x12\x1a\n" +
	"\bhasValue\x18\x01 \x01(\bR\bhasValue\">\n" +
	"\x14SetRemoveMemberInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"/\n" +
	"\x15SetRemoveMemberOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"Z\n" +
	"\x16InsertToSortedSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x18\n" +
	"\amainKey\x18\x03 \x01(\tR\amainKey\"1\n" +
	"\x17InsertToSortedSetOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"F\n" +
	"\x18RemoveFromSortedSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amainKey\x18\x02 \x01(\tR\amainKey\"3\n" +
	"\x19RemoveFromSortedSetOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"D\n" +
	"\x16GetScoreSortedSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amainKey\x18\x02 \x01(\tR\amainKey\"/\n" +
	"\x17GetScoreSortedSetOutput\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\"C\n" +
	"\x15GetRankSortedSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amainKey\x18\x02 \x01(\tR\amainKey\",\n" +
	"\x16GetRankSortedSetOutput\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\"/\n" +
	"\x13GetRankMembersInput\x12\x18\n" +
	"\amainKey\x18\x01 \x01(\tR\amainKey\"O\n" +
	"\x14GetRankMembersOutput\x127\n" +
	"\x0fmembersAndScore\x18\x01 \x03(\v2\r.ScoreAndNameR\x0fmembersAndScore\"8\n" +
	"\fScoreAndName\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x98\b\n" +
	"\rCacheInteract\x12.\n" +
	"\tMapInsert\x12\x0f.MapInsertInput\x1a\x10.MapInsertResult\x12+\n" +
	"\bMapFetch\x12\x0e.MapFetchInput\x1a\x0f.MapFetchResult\x12.\n" +
	"\tMapDelete\x12\x0f.MapDeleteInput\x1a\x10.MapDeleteResult\x129\n" +
	"\x10QueueInsertFront\x12\x11.QueueInsertInput\x1a\x12.QueueInsertOutput\x128\n" +
	"\x0fQueueInsertBack\x12\x11.QueueInsertInput\x1a\x12.QueueInsertOutput\x129\n" +
	"\x10QueueRemoveFront\x12\x11.QueueRemoveInput\x1a\x12.QueueRemoveOutput\x128\n" +
	"\x0fQueueRemoveBack\x12\x11.QueueRemoveInput\x1a\x12.QueueRemoveOutput\x124\n" +
	"\vInsertToSet\x12\x11.InsertToSetInput\x1a\x12.InsertToSetOutput\x127\n" +
	"\fGetSetValues\x12\x12.GetSetValuesInput\x1a\x13.GetSetValuesOutput\x127\n" +
	"\fSetHasMember\x12\x12.SetHasMemberInput\x1a\x13.SetHasMemberOutput\x12@\n" +
	"\x0fSetRemoveMember\x12\x15.SetRemoveMemberInput\x1a\x16.SetRemoveMemberOutput\x12F\n" +
	"\x11InsertToSortedSet\x12\x17.InsertToSortedSetInput\x1a\x18.InsertToSortedSetOutput\x12L\n" +
	"\x13RemoveFromSortedSet\x12\x19.RemoveFromSortedSetInput\x1a\x1a.RemoveFromSortedSetOutput\x12F\n" +
	"\x11GetScoreSortedSet\x12\x17.GetScoreSortedSetInput\x1a\x18.GetScoreSortedSetOutput\x12C\n" +
	"\x10GetRankSortedSet\x12\x16.GetRankSortedSetInput\x1a\x17.GetRankSortedSetOutput\x12@\n" +
	"\x11GetRankMembersAsc\x12\x14.GetRankMembersInput\x1a\x15.GetRankMembersOutput\x12A\n" +
	"\x12GetRankMembersDesc\x12\x14.GetRankMembersInput\x1a\x15.GetRankMembersOutputB\bZ\x06proto/b\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_data_proto_goTypes = []any{
	(*MapInsertInput)(nil),            // 0: MapInsertInput
	(*MapFetchInput)(nil),             // 1: MapFetchInput
	(*MapDeleteInput)(nil),            // 2: MapDeleteInput
	(*MapInsertResult)(nil),           // 3: MapInsertResult
	(*MapFetchResult)(nil),            // 4: MapFetchResult
	(*MapDeleteResult)(nil),           // 5: MapDeleteResult
	(*QueueInsertInput)(nil),          // 6: QueueInsertInput
	(*QueueInsertOutput)(nil),         // 7: QueueInsertOutput
	(*QueueRemoveInput)(nil),          // 8: QueueRemoveInput
	(*QueueRemoveOutput)(nil),         // 9: QueueRemoveOutput
	(*InsertToSetInput)(nil),          // 10: InsertToSetInput
	(*InsertToSetOutput)(nil),         // 11: InsertToSetOutput
	(*GetSetValuesInput)(nil),         // 12: GetSetValuesInput
	(*GetSetValuesOutput)(nil),        // 13: GetSetValuesOutput
	(*SetHasMemberInput)(nil),         // 14: SetHasMemberInput
	(*SetHasMemberOutput)(nil),        // 15: SetHasMemberOutput
	(*SetRemoveMemberInput)(nil),      // 16: SetRemoveMemberInput
	(*SetRemoveMemberOutput)(nil),     // 17: SetRemoveMemberOutput
	(*InsertToSortedSetInput)(nil),    // 18: InsertToSortedSetInput
	(*InsertToSortedSetOutput)(nil),   // 19: InsertToSortedSetOutput
	(*RemoveFromSortedSetInput)(nil),  // 20: RemoveFromSortedSetInput
	(*RemoveFromSortedSetOutput)(nil), // 21: RemoveFromSortedSetOutput
	(*GetScoreSortedSetInput)(nil),    // 22: GetScoreSortedSetInput
	(*GetScoreSortedSetOutput)(nil),   // 23: GetScoreSortedSetOutput
	(*GetRankSortedSetInput)(nil),     // 24: GetRankSortedSetInput
	(*GetRankSortedSetOutput)(nil),    // 25: GetRankSortedSetOutput
	(*GetRankMembersInput)(nil),       // 26: GetRankMembersInput
	(*GetRankMembersOutput)(nil),      // 27: GetRankMembersOutput
	(*ScoreAndName)(nil),              // 28: ScoreAndName
}
var file_data_proto_depIdxs = []int32{
	28, // 0: GetRankMembersOutput.membersAndScore:type_name -> ScoreAndName
	0,  // 1: CacheInteract.MapInsert:input_type -> MapInsertInput
	1,  // 2: CacheInteract.MapFetch:input_type -> MapFetchInput
	2,  // 3: CacheInteract.MapDelete:input_type -> MapDeleteInput
	6,  // 4: CacheInteract.QueueInsertFront:input_type -> QueueInsertInput
	6,  // 5: CacheInteract.QueueInsertBack:input_type -> QueueInsertInput
	8,  // 6: CacheInteract.QueueRemoveFront:input_type -> QueueRemoveInput
	8,  // 7: CacheInteract.QueueRemoveBack:input_type -> QueueRemoveInput
	10, // 8: CacheInteract.InsertToSet:input_type -> InsertToSetInput
	12, // 9: CacheInteract.GetSetValues:input_type -> GetSetValuesInput
	14, // 10: CacheInteract.SetHasMember:input_type -> SetHasMemberInput
	16, // 11: CacheInteract.SetRemoveMember:input_type -> SetRemoveMemberInput
	18, // 12: CacheInteract.InsertToSortedSet:input_type -> InsertToSortedSetInput
	20, // 13: CacheInteract.RemoveFromSortedSet:input_type -> RemoveFromSortedSetInput
	22, // 14: CacheInteract.GetScoreSortedSet:input_type -> GetScoreSortedSetInput
	24, // 15: CacheInteract.GetRankSortedSet:input_type -> GetRankSortedSetInput
	26, // 16: CacheInteract.GetRankMembersAsc:input_type -> GetRankMembersInput
	26, // 17: CacheInteract.GetRankMembersDesc:input_type -> GetRankMembersInput
	3,  // 18: CacheInteract.MapInsert:output_type -> MapInsertResult
	4,  // 19: CacheInteract.MapFetch:output_type -> MapFetchResult
	5,  // 20: CacheInteract.MapDelete:output_type -> MapDeleteResult
	7,  // 21: CacheInteract.QueueInsertFront:output_type -> QueueInsertOutput
	7,  // 22: CacheInteract.QueueInsertBack:output_type -> QueueInsertOutput
	9,  // 23: CacheInteract.QueueRemoveFront:output_type -> QueueRemoveOutput
	9,  // 24: CacheInteract.QueueRemoveBack:output_type -> QueueRemoveOutput
	11, // 25: CacheInteract.InsertToSet:output_type -> InsertToSetOutput
	13, // 26: CacheInteract.GetSetValues:output_type -> GetSetValuesOutput
	15, // 27: CacheInteract.SetHasMember:output_type -> SetHasMemberOutput
	17, // 28: CacheInteract.SetRemoveMember:output_type -> SetRemoveMemberOutput
	19, // 29: CacheInteract.InsertToSortedSet:output_type -> InsertToSortedSetOutput
	21, // 30: CacheInteract.RemoveFromSortedSet:output_type -> RemoveFromSortedSetOutput
	23, // 31: CacheInteract.GetScoreSortedSet:output_type -> GetScoreSortedSetOutput
	25, // 32: CacheInteract.GetRankSortedSet:output_type -> GetRankSortedSetOutput
	27, // 33: CacheInteract.GetRankMembersAsc:output_type -> GetRankMembersOutput
	27, // 34: CacheInteract.GetRankMembersDesc:output_type -> GetRankMembersOutput
	18, // [18:35] is the sub-list for method output_type
	1,  // [1:18] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
