// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapInsertInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertInput) Reset() {
	*x = MapInsertInput{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertInput) ProtoMessage() {}

func (x *MapInsertInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertInput.ProtoReflect.Descriptor instead.
func (*MapInsertInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *MapInsertInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapInsertInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapFetchInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchInput) Reset() {
	*x = MapFetchInput{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchInput) ProtoMessage() {}

func (x *MapFetchInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchInput.ProtoReflect.Descriptor instead.
func (*MapFetchInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *MapFetchInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapDeleteInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteInput) Reset() {
	*x = MapDeleteInput{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteInput) ProtoMessage() {}

func (x *MapDeleteInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteInput.ProtoReflect.Descriptor instead.
func (*MapDeleteInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *MapDeleteInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapInsertResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapInsertResult) Reset() {
	*x = MapInsertResult{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInsertResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInsertResult) ProtoMessage() {}

func (x *MapInsertResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInsertResult.ProtoReflect.Descriptor instead.
func (*MapInsertResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *MapInsertResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type MapFetchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapFetchResult) Reset() {
	*x = MapFetchResult{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapFetchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapFetchResult) ProtoMessage() {}

func (x *MapFetchResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapFetchResult.ProtoReflect.Descriptor instead.
func (*MapFetchResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *MapFetchResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MapDeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDeleteResult) Reset() {
	*x = MapDeleteResult{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDeleteResult) ProtoMessage() {}

func (x *MapDeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDeleteResult.ProtoReflect.Descriptor instead.
func (*MapDeleteResult) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *MapDeleteResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type QueueInsertInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInsertInput) Reset() {
	*x = QueueInsertInput{}
	mi := &file_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInsertInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInsertInput) ProtoMessage() {}

func (x *QueueInsertInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInsertInput.ProtoReflect.Descriptor instead.
func (*QueueInsertInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{6}
}

func (x *QueueInsertInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QueueInsertInput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type QueueInsertOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInsertOutput) Reset() {
	*x = QueueInsertOutput{}
	mi := &file_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInsertOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInsertOutput) ProtoMessage() {}

func (x *QueueInsertOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInsertOutput.ProtoReflect.Descriptor instead.
func (*QueueInsertOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{7}
}

func (x *QueueInsertOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type QueueRemoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemoveInput) Reset() {
	*x = QueueRemoveInput{}
	mi := &file_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveInput) ProtoMessage() {}

func (x *QueueRemoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveInput.ProtoReflect.Descriptor instead.
func (*QueueRemoveInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{8}
}

func (x *QueueRemoveInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type QueueRemoveOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRemoveOutput) Reset() {
	*x = QueueRemoveOutput{}
	mi := &file_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRemoveOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRemoveOutput) ProtoMessage() {}

func (x *QueueRemoveOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRemoveOutput.ProtoReflect.Descriptor instead.
func (*QueueRemoveOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{9}
}

func (x *QueueRemoveOutput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertToSetInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []string               `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSetInput) Reset() {
	*x = InsertToSetInput{}
	mi := &file_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSetInput) ProtoMessage() {}

func (x *InsertToSetInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSetInput.ProtoReflect.Descriptor instead.
func (*InsertToSetInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{10}
}

func (x *InsertToSetInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InsertToSetInput) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertToSetOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertToSetOutput) Reset() {
	*x = InsertToSetOutput{}
	mi := &file_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertToSetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertToSetOutput) ProtoMessage() {}

func (x *InsertToSetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertToSetOutput.ProtoReflect.Descriptor instead.
func (*InsertToSetOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{11}
}

func (x *InsertToSetOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetSetValuesInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetValuesInput) Reset() {
	*x = GetSetValuesInput{}
	mi := &file_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetValuesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetValuesInput) ProtoMessage() {}

func (x *GetSetValuesInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetValuesInput.ProtoReflect.Descriptor instead.
func (*GetSetValuesInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{12}
}

func (x *GetSetValuesInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSetValuesOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetValuesOutput) Reset() {
	*x = GetSetValuesOutput{}
	mi := &file_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetValuesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetValuesOutput) ProtoMessage() {}

func (x *GetSetValuesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetValuesOutput.ProtoReflect.Descriptor instead.
func (*GetSetValuesOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{13}
}

func (x *GetSetValuesOutput) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetHasMemberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHasMemberInput) Reset() {
	*x = SetHasMemberInput{}
	mi := &file_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHasMemberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHasMemberInput) ProtoMessage() {}

func (x *SetHasMemberInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHasMemberInput.ProtoReflect.Descriptor instead.
func (*SetHasMemberInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{14}
}

func (x *SetHasMemberInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetHasMemberInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetHasMemberOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasValue      bool                   `protobuf:"varint,1,opt,name=hasValue,proto3" json:"hasValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHasMemberOutput) Reset() {
	*x = SetHasMemberOutput{}
	mi := &file_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHasMemberOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHasMemberOutput) ProtoMessage() {}

func (x *SetHasMemberOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHasMemberOutput.ProtoReflect.Descriptor instead.
func (*SetHasMemberOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{15}
}

func (x *SetHasMemberOutput) GetHasValue() bool {
	if x != nil {
		return x.HasValue
	}
	return false
}

type SetRemoveMemberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoveMemberInput) Reset() {
	*x = SetRemoveMemberInput{}
	mi := &file_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveMemberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveMemberInput) ProtoMessage() {}

func (x *SetRemoveMemberInput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveMemberInput.ProtoReflect.Descriptor instead.
func (*SetRemoveMemberInput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{16}
}

func (x *SetRemoveMemberInput) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRemoveMemberInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRemoveMemberOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRemoveMemberOutput) Reset() {
	*x = SetRemoveMemberOutput{}
	mi := &file_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveMemberOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveMemberOutput) ProtoMessage() {}

func (x *SetRemoveMemberOutput) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveMemberOutput.ProtoReflect.Descriptor instead.
func (*SetRemoveMemberOutput) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{17}
}

func (x *SetRemoveMemberOutput) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\"8\n" +
	"\x0eMapInsertInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"!\n" +
	"\rMapFetchInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\"\n" +
	"\x0eMapDeleteInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x0fMapInsertResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"&\n" +
	"\x0eMapFetchResult\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\")\n" +
	"\x0fMapDeleteResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\":\n" +
	"\x10QueueInsertInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"+\n" +
	"\x11QueueInsertOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"$\n" +
	"\x10QueueRemoveInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11QueueRemoveOutput\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\":\n" +
	"\x10InsertToSetInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"+\n" +
	"\x11InsertToSetOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\"%\n" +
	"\x11GetSetValuesInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\",\n" +
	"\x12GetSetValuesOutput\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\";\n" +
	"\x11SetHasMemberInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"0\n" +
	"\x12SetHasMemberOutput\x12\x1a\n" +
	"\bhasValue\x18\x01 \x01(\bR\bhasValue\">\n" +
	"\x14SetRemoveMemberInput\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"/\n" +
	"\x15SetRemoveMemberOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\xf0\x04\n" +
	"\rCacheInteract\x12.\n" +
	"\tMapInsert\x12\x0f.MapInsertInput\x1a\x10.MapInsertResult\x12+\n" +
	"\bMapFetch\x12\x0e.MapFetchInput\x1a\x0f.MapFetchResult\x12.\n" +
	"\tMapDelete\x12\x0f.MapDeleteInput\x1a\x10.MapDeleteResult\x129\n" +
	"\x10QueueInsertFront\x12\x11.QueueInsertInput\x1a\x12.QueueInsertOutput\x128\n" +
	"\x0fQueueInsertBack\x12\x11.QueueInsertInput\x1a\x12.QueueInsertOutput\x129\n" +
	"\x10QueueRemoveFront\x12\x11.QueueRemoveInput\x1a\x12.QueueRemoveOutput\x128\n" +
	"\x0fQueueRemoveBack\x12\x11.QueueRemoveInput\x1a\x12.QueueRemoveOutput\x124\n" +
	"\vInsertToSet\x12\x11.InsertToSetInput\x1a\x12.InsertToSetOutput\x127\n" +
	"\fGetSetValues\x12\x12.GetSetValuesInput\x1a\x13.GetSetValuesOutput\x127\n" +
	"\fSetHasMember\x12\x12.SetHasMemberInput\x1a\x13.SetHasMemberOutput\x12@\n" +
	"\x0fSetRemoveMember\x12\x15.SetRemoveMemberInput\x1a\x16.SetRemoveMemberOutputB\bZ\x06proto/b\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_data_proto_goTypes = []any{
	(*MapInsertInput)(nil),        // 0: MapInsertInput
	(*MapFetchInput)(nil),         // 1: MapFetchInput
	(*MapDeleteInput)(nil),        // 2: MapDeleteInput
	(*MapInsertResult)(nil),       // 3: MapInsertResult
	(*MapFetchResult)(nil),        // 4: MapFetchResult
	(*MapDeleteResult)(nil),       // 5: MapDeleteResult
	(*QueueInsertInput)(nil),      // 6: QueueInsertInput
	(*QueueInsertOutput)(nil),     // 7: QueueInsertOutput
	(*QueueRemoveInput)(nil),      // 8: QueueRemoveInput
	(*QueueRemoveOutput)(nil),     // 9: QueueRemoveOutput
	(*InsertToSetInput)(nil),      // 10: InsertToSetInput
	(*InsertToSetOutput)(nil),     // 11: InsertToSetOutput
	(*GetSetValuesInput)(nil),     // 12: GetSetValuesInput
	(*GetSetValuesOutput)(nil),    // 13: GetSetValuesOutput
	(*SetHasMemberInput)(nil),     // 14: SetHasMemberInput
	(*SetHasMemberOutput)(nil),    // 15: SetHasMemberOutput
	(*SetRemoveMemberInput)(nil),  // 16: SetRemoveMemberInput
	(*SetRemoveMemberOutput)(nil), // 17: SetRemoveMemberOutput
}
var file_data_proto_depIdxs = []int32{
	0,  // 0: CacheInteract.MapInsert:input_type -> MapInsertInput
	1,  // 1: CacheInteract.MapFetch:input_type -> MapFetchInput
	2,  // 2: CacheInteract.MapDelete:input_type -> MapDeleteInput
	6,  // 3: CacheInteract.QueueInsertFront:input_type -> QueueInsertInput
	6,  // 4: CacheInteract.QueueInsertBack:input_type -> QueueInsertInput
	8,  // 5: CacheInteract.QueueRemoveFront:input_type -> QueueRemoveInput
	8,  // 6: CacheInteract.QueueRemoveBack:input_type -> QueueRemoveInput
	10, // 7: CacheInteract.InsertToSet:input_type -> InsertToSetInput
	12, // 8: CacheInteract.GetSetValues:input_type -> GetSetValuesInput
	14, // 9: CacheInteract.SetHasMember:input_type -> SetHasMemberInput
	16, // 10: CacheInteract.SetRemoveMember:input_type -> SetRemoveMemberInput
	3,  // 11: CacheInteract.MapInsert:output_type -> MapInsertResult
	4,  // 12: CacheInteract.MapFetch:output_type -> MapFetchResult
	5,  // 13: CacheInteract.MapDelete:output_type -> MapDeleteResult
	7,  // 14: CacheInteract.QueueInsertFront:output_type -> QueueInsertOutput
	7,  // 15: CacheInteract.QueueInsertBack:output_type -> QueueInsertOutput
	9,  // 16: CacheInteract.QueueRemoveFront:output_type -> QueueRemoveOutput
	9,  // 17: CacheInteract.QueueRemoveBack:output_type -> QueueRemoveOutput
	11, // 18: CacheInteract.InsertToSet:output_type -> InsertToSetOutput
	13, // 19: CacheInteract.GetSetValues:output_type -> GetSetValuesOutput
	15, // 20: CacheInteract.SetHasMember:output_type -> SetHasMemberOutput
	17, // 21: CacheInteract.SetRemoveMember:output_type -> SetRemoveMemberOutput
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
